[build-system]
requires = ["pyelftools >= 0.32"]

[tool.pyright]
reportAny = false
reportExplicitAny = false
reportUnknownVariableType = false
reportUnknownMemberType = false
reportUnknownArgumentType = false
